apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:16.1.1
        env: 
        - name: DB_VENDOR
          value: "POSTGRES"
        - name: DB_ADDR
          value: "host.minikube.internal"
        - name: DB_PORT
          value: "5433"
        - name: DB_DATABASE
          value: "keycloakdb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"