version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local

services:
  rabbitmq:
    build: rabbitmq:3.11.3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      STOMP_DEFAULT_USER: admin
      STOMP_DEFAULT_PASSWORD: admin
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - internal